apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-app-py-deployment
  labels:
    app: simple-app-py
    environment: test
    tier: frontend 
spec:
  selector:
    matchLabels:
      app: simple-app-py
      environment: test
  replicas: 3
  template:
    metadata:
      name: 
      labels:
        app: simple-app-py
        environment: test
    spec:
      containers:
        - name: simple-app-py
          image: 